### ISSUE TITLE
FATA[0001] Couldn't find site  

### ISSUE THREAD

**Issue by xmarwin** [mannkind/unifi2mqtt#12]
Hello.
I am trying to run this software on my Synology (under Docker) and I keep getting this error:

FATA[0001] Couldn't find site                            error="self/sites returned result code: error"

this is the log:
![obrazek](https://user-images.githubusercontent.com/10614100/71675687-9b214700-2d7e-11ea-8b89-c6726b36eb93.png)

and here is the configuration:
![obrazek](https://user-images.githubusercontent.com/10614100/71675890-2995c880-2d7f-11ea-9622-6fb2f4157fd6.png)

Any ideas, how to make this work?
Thanks a lot, Martin

**Comment by mannkind** [comment]
Martin,

My initial guess would be that unless you’re running a multi-site controller, you should unset UNIFI_SITE. Just use the default site of “default”. 

If you’re running a multi-site controller, then the library used in this app expects the ID; example “ohmt4ch6” for a site named “Home”. You can find the ID using the link to the site found in the “site overview” screen. 

Hope that helps!

**Comment by xmarwin** [comment]
Hello,
I figured it out - I didn't set up UNIFI_USERNAME (mine is different from default). Now it works. However, the error message is a bit confusing.

Best regards, Martin
